### ISSUE TITLE
Filewatcher is not reporting events in CIFS mounts

### ISSUE THREAD

**Issue by shsms** [frequenz-floss/frequenz-channels-python#256]
### What happened?

A lot of cloud use-cases for FileWatcher need it to be monitoring NFS/CIFS mounts, which don't emit inotify events on remote updates.

So our FileWatcher which uses the `watchfiles` library, doesn't emit events either.  An alternative is for the FileWatcher to use the [watchdog](https://github.com/gorakhargosh/watchdog#about-using-watchdog-with-cifs) library, which also has a polling observer.

### What did you expect instead?

FS events triggered remotely also produce a message from the FileWatcher.

### Affected part(s)

Utility receivers, `Event`, `FileWatcher`, `Timer`, etc. (part:receivers)

**Comment by llucax** [comment]
Whoops, this might need to be opened in https://github.com/samuelcolvin/watchfiles instead, I don't think there is much we can do in here... And it might be that they can't do much in there either, unless there is some active polling, it is probably a kernel thing...

**Comment by shsms** [comment]
Not sure if you saw the `watchdog` link I mentioned in the description.  It is a completely different package than `watchfiles`, and has a polling implementation, specifically made for CIFS.

**Comment by llucax** [comment]
> Not sure if you saw the `watchdog` link I mentioned in the description. It is a completely different package than `watchfiles`, and has a polling implementation, specifically made for CIFS.

Whoops! No, I haven't seen it, sorry. Will hide the comments to reduce the noise.

**Comment by daniel-zullo-frequenz** [comment]
[watchfiles](https://github.com/samuelcolvin/watchfiles) has the option `force_polling` that can be set either by setting the function parameter or setting an environment variable
https://github.com/samuelcolvin/watchfiles/blob/main/watchfiles/main.py#L184-L185

That should probably solve the issue with `Filewatcher` not reporting events in CIFS mounts

**Comment by llucax** [comment]
I would say we add a `*, disable_polling: bool = False` option to the `FileWatcher` constructor and pass it negated as `force_polling` to `watchfiles` to close this issue. Can you submit a PR @daniel-zullo-frequenz ?
