### ISSUE TITLE
Allow sending `None`

### ISSUE THREAD

**Issue by leandro-lucarella-frequenz** [frequenz-floss/frequenz-channels-python#26]
### What's needed?

Users should be able to send **any** value through a channel (or at least any serializable value if at some point channels can be over the wire). This includes `None`.

### Proposed solution

Allow sending `None` by raising an exception instead of returning `None` if a channel is closed.

### Alternatives and workarounds

Wrapping the `None` in another type (like `(None,)`).

**Comment by shsms** [comment]
This would require internal representations to not use None to signal an empty channel.  A sentinal value could be used instead,  as suggested here: https://github.com/frequenz-floss/frequenz-channels-python/pull/42/files/206bbd7a056c32c452281a1bf390d12035f9f244#r1021864402

**Comment by shsms** [comment]
Done in #83
