### ISSUE TITLE
Rename `LatestValueCache.get()` to `value` and make it a `@property`

### ISSUE THREAD

**Issue by llucax** [frequenz-floss/frequenz-channels-python#306]
I think I could make sense to rename `get()` to `value` and make it a `@property`.

_Originally posted by @llucax in https://github.com/frequenz-floss/frequenz-channels-python/pull/302#pullrequestreview-2151374660_

**Comment by shsms** [comment]
I guess the only concern is that this could raise an exception when no value has been received.  It feels a bit weird to have properties that can raise.

**Comment by llucax** [comment]
Interesting point. I'm pretty sure we have some properties that raise exceptions, I always thought it was fine because accessing an attribute ultimately can always raise a `AttributeError`, but when using type hints and a checker, that really shouldn't happen.

On the other hand, I like the simplicity of a property syntax when the expected case is that it should work (this should only raise during "initialization"), which I think is kind of the pattern I've been using.

Probably this needs some discussion. Ideally I would like to make a decision and try to stick with it so we have some consistency about this.

**Comment by llucax** [comment]
@frequenz-floss/python-sdk-team FYI.

**Comment by shsms** [comment]
> (this should only raise during "initialization")

but that could be a long time, and sometimes not even when expected, because of broken data source or connection.

**Comment by shsms** [comment]
We decided not to do this, so that we don't have properties that can raise.
