### ISSUE TITLE
FileWatcher stops working after exiting async iterator

### ISSUE THREAD

**Issue by daniel-zullo-frequenz** [frequenz-floss/frequenz-channels-python#317]
### What happened?

The `FileWatcher` breaks after exiting an async iterator when the task running it gets cancelled, `FileWatcher` enters an infinite loop where `ready()` continuously returns False, and `consume()` raises an error. The underlying issue seems to be that `self._awatch_stopped_exc` is never cleared after cancellation and `self._awatch` seems broken.

### What did you expect instead?

The `FileWatcher` should continue working if it is reused in a new async iterator, without needing to be re-instantiated.

### Affected part(s)

Utilities (`Event`, `FileWatcher`, `Timer`, etc.) (part:utilities)

### Extra information

The following script reproduces the issue and is similar to what the `ConfigManagingActor` in the frequenz-SDK does. If the actor is restarted for any reason, the `FileWatcher` stops working and only works again if re-created.

```python
import asyncio
from datetime import timedelta
from pathlib import Path

from frequenz.channels import select, selected_from
from frequenz.channels.file_watcher import EventType, FileWatcher
from frequenz.channels.timer import SkipMissedAndDrift, Timer


async def read(file_path, file_watcher) -> None:
    """Read file events."""
    timer_write = Timer(timedelta(seconds=1), SkipMissedAndDrift())

    async for selected in select(file_watcher, timer_write):
        if selected_from(selected, file_watcher):
            print(f"New file event: {selected.message}")
        elif selected_from(selected, timer_write):
            file_path.write_text(f"{selected.message}")
            print(f"Writing {selected.message} to file: {file_path}")
        else:
            print("Unknown selected")


async def run():
    file_path = Path("config.txt")

    file_watcher = FileWatcher(
        paths=[file_path.parent], event_types=frozenset(EventType)
    )

    task = asyncio.create_task(read(file_path, file_watcher))

    timer_stop = Timer(timedelta(seconds=3), SkipMissedAndDrift())

    while True:
        await timer_stop.receive()
        task.cancel()
        print("Task cancelled. New task will be created.")
        await asyncio.sleep(0.1)
        task = asyncio.create_task(read(file_path, file_watcher))


asyncio.run(run())
```

**Comment by daniel-zullo-frequenz** [comment]
The CancelledError causes the exit of the [awatch() loop](https://github.com/samuelcolvin/watchfiles/blob/main/watchfiles/main.py#L257-L260)
So it seems there is no other way around than recreating awatch()
A possible solution might be something around this:

```diff
diff --git a/src/frequenz/channels/file_watcher.py b/src/frequenz/channels/file_watcher.py
index 57c3553..50ee0da 100644
--- a/src/frequenz/channels/file_watcher.py
+++ b/src/frequenz/channels/file_watcher.py
@@ -156,6 +156,15 @@ class FileWatcher(Receiver[Event]):
         """
         return change in [event_type.value for event_type in self.event_types]
 
+    def _reset(self) -> None:
+        """Reset the state of this receiver."""
+        self._awatch_stopped_exc = None
+        self._stop_event.clear()
+        self._awatch = awatch(
+            *self._paths, stop_event=self._stop_event, watch_filter=self._filter_events
+        )
+
     def __del__(self) -> None:
         """Finalize this file watcher."""
         # We need to set the stop event to make sure that the awatch background task
@@ -179,12 +188,16 @@ class FileWatcher(Receiver[Event]):
 
         # if it was already stopped, return immediately.
         if self._awatch_stopped_exc is not None:
-            return False
+            if self._stop_event.is_set():
+                self._reset()
+            else:
+                return False
 
         try:
             self._changes = await anext(self._awatch)
         except StopAsyncIteration as err:
             self._awatch_stopped_exc = err
+            return False
 
         return True
 
```

**Comment by llucax** [comment]
> So it seems there is no other way around than recreating awatch()

Which I think it makes sense, if you cancel any task you need to re-create it to run again.

**Comment by llucax** [comment]
I think I would need to look into this in more detail, but my feeling is we need to handle `CancelledError` somewhere instead. It feels weird that we just try to resurrect any dead awatch (because this is not only restarting a cancelled awatch, is treating any failure the same, right?). But I don't know, maybe I'm wrong, again I haven't looked at this code for a long while now so I'm not very familiar with it.

Looking at it a bit more, but still not super in depth, my feeling is we need a `start()`/`stop()` method for this (hello `BackgroundService`/`Service` again!), we should fix the bug and `return False` from `ready()` if it is stopped, and if for some reason you stopped it (for example, you indirectly cancelled the file watcher), then you, the user of the file watcher, like the config manager, should start the file watcher again. IMHO that looks like a more clear solution.

**Comment by daniel-zullo-frequenz** [comment]
> we should fix the bug and return False from ready() if it is stopped,

I'm afraid it won't make any difference as the receiver does not check for the return value of ready()
https://github.com/frequenz-floss/frequenz-channels-python/blob/v1.x.x/src/frequenz/channels/_receiver.py#L177-L181


> and if for some reason you stopped it (for example, you indirectly cancelled the file watcher), then you, the user of the file watcher, like the config manager, should start the file watcher again. IMHO that looks like a more clear solution.

Then the user just needs a fresh FileWatcher before entering/calling the async iterator.

Initially, I was not clear to me whether this issue needed to be fixed in the SDK or Channels. My proposed solution was to reuse the existing FileWatcher within Channels, but this approach is not aligned with the current code. The code assumes that the FileWatcher becomes unusable after an exception or stop event is triggered.

**Comment by llucax** [comment]
> I'm afraid it won't make any difference as the receiver does not check for the return value of ready()

```py
        try:
            await self.ready()
            return self.consume()
        except ReceiverStoppedError as exc:
            raise StopAsyncIteration() from exc
```
No, this should work. `self.consume()` should raise the `ReceiverStoppedError`, so the iteration should be stopped here.

**Comment by llucax** [comment]
> Initially, I was not clear to me whether this issue needed to be fixed in the SDK or Channels. My proposed solution was to reuse the existing FileWatcher within Channels, but this approach is not aligned with the current code. The code assumes that the FileWatcher becomes unusable after an exception or stop event is triggered.

Yeah, I think this is because it is not considered normal that this receiver is stopped, it is sort of considered an error.

There is still a bug in the file watcher, that missing `return False` is definitely wrong and we need to fix it. Then we could either make the file watcher stoppable and restatable or, as you said, we could just create a new one when it is stopped. Maybe the later is the simplest approach right now, but stop/start a file watcher doesn't sound like a bad idea at all, so I'd be happy to accept a PR to do that.

**Comment by daniel-zullo-frequenz** [comment]
@llucax I'm not sure if got right what you have in mind. I've created a draft #318 and we can discuss there what you'd like to do to improve/fix the FileWatcher
