### ISSUE TITLE
Fix `FileWatcher` ordering bug

### ISSUE THREAD

**Issue by shsms** [frequenz-floss/frequenz-channels-python#51]
It looks like ordering is important here and I don't think `set` preserves order. Also, why do we want to compress `FileChange`s that are the same, suppose we have this sequence:

1. `/a` is added
2. `/a` is deleted
3. `/a` is added again

With this implementation we could only get one add and one deletion so we would think the file doesn't exist but it does.

If this introduced a bug that wasn't detected by test, we should probably add a test for this too :)

_Originally posted by @leandro-lucarella-frequenz in https://github.com/frequenz-floss/frequenz-channels-python/pull/42#discussion_r1022004996_

**Comment by shsms** [comment]
There's also:  https://github.com/frequenz-floss/frequenz-channels-python/pull/42#discussion_r1022009051

**Comment by leandro-lucarella-frequenz** [comment]
> There's also: [#42 (comment)](https://github.com/frequenz-floss/frequenz-channels-python/pull/42#discussion_r1022009051)

Created #53 for this.

**Comment by leandro-lucarella-frequenz** [comment]
Looking more closely at [`watchfiles` documentation](https://watchfiles.helpmanual.io/api/watch/#watchfiles.awatch), it looks like the library doens't really provide ordering anyway, as it yields a `Set[FileChange]`.

So closing as invalid.
